app/snap/models.py
from app import db


class Snap(db.Model):
    __tablename__ = 'snap'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users_user.id'))
    date = db.Column(db.String(200))
    title = db.Column(db.String(200))
    mini = db.Column(db.String(200))
    imgName = db.Column(db.String(200))

    def __init__(self, title, mini, imgName, user_id):
        self.title = title
        self.mini = mini
        self.imgName = imgName
        self.user_id = user_id


    def setSnap(self, imgName):
        self.imgName = imgName

    def getMini(self):
        return self.mini

app/users/models.py
from app import db
from app.snap.models import Snap 

class User(db.Model):
    __tablename__ = 'users_user'

    id = db.Column(db.Integer, primary_key=True)
    userEmail = db.Column(db.String(80), unique=True)
    userPassword = db.Column(db.String(80))
    snap = db.relationship('Snap', backref='user', lazy='dynamic')



    def __init__(self, email, password):
        self.userEmail = email
        self.userPassword = password

    def __repr__(self):
        return '<User %r>' % (self.userEmail)

    def getId(self):
        return self.id

app/__init__.py
from flask import Flask, render_template, jsonify
from flask.ext.sqlalchemy import SQLAlchemy


app = Flask(__name__)
app.config.from_object('config')

db = SQLAlchemy(app)


@app.route('/')
def index():
    return render_template('home.html')


#@app.route('/json')
#def json():
#
#        #    userSnap = Snap.query.filter_by(user_id = session['user_id'])
#        #snapList = [dict(date = snap.date, title=snap.title, mini=snap.mini, img=snap.imgName) for snap in userSnap]
#        #return render_template('flow.html', snapList = snapList)
#
#    userSnap = Snap.query.all()
#    snapList = [dict(date = snap.date, title=snap.title, mini=snap.mini, img=snap.imgName) for snap in userSnap]
#    list = [
#        {'image':'http://static.inven.co.kr/image_2011/site_image/lol/dataninfo/icon/skinfull/xinzhao_splash_4.jpg', 'title': "title1", 'mini': "mine1"},
#        {'image':'http://static.inven.co.kr/image_2011/site_image/lol/dataninfo/icon/skinfull/xinzhao_splash_4.jpg', 'title': "title2", 'mini': "mine2"},
#        {'image': '/Users/YoungNamLee/git/dailySnapApp/button.png'}
#    ]
#    return jsonify(result=snapList)


#<div><img src="../static/uploads/{{snap.img}}" alt="{{snap.img}}"></div>
#    a = jsonify(image='http://static.inven.co.kr/image_2011/site_image/lol/dataninfo/icon/skinfull/xinzhao_splash_4.jpg')
 #   print type(a)
  #  return a


from app.users.views import mod as usersModule
from app.snap.views import mod as snapModule
from app.flow.views import mod as flowModule

app.register_blueprint(usersModule)
app.register_blueprint(snapModule)
app.register_blueprint(flowModule)

app/flow/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask import Flask, make_response, redirect, session, url_for

from app import db
from app.users.models import User
from app.snap.models import Snap

mod = Blueprint('flow', __name__, url_prefix='/flow')

@mod.route('')
def flows():
    if User.query.filter_by(id = session['user_id']).first():
        userSnap = Snap.query.filter_by(user_id = session['user_id'])
        snapList = [dict(date = snap.date, title=snap.title, mini=snap.mini, img=snap.imgName) for snap in userSnap]
        return render_template('flow.html', snapList = snapList)

    else:
        return redirect(url_for('index'))

app/snap/views.py
import os
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, jsonify
from werkzeug.utils import secure_filename
from app import db, app
from app.snap.models import Snap
from app.users.models import User

mod = Blueprint('snap', __name__, url_prefix='/snap')
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])


#SnapUpload
def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@mod.route('/json')
def json():

        #    userSnap = Snap.query.filter_by(user_id = session['user_id'])
        #snapList = [dict(date = snap.date, title=snap.title, mini=snap.mini, img=snap.imgName) for snap in userSnap]
        #return render_template('flow.html', snapList = snapList)

    userSnap = Snap.query.all()
    snapList = [dict(title=snap.title, mini=snap.mini, image="http://0.0.0.0:7000/static/uploads/"+snap.imgName) for snap in userSnap]

    return jsonify(result=snapList)

@mod.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        file = request.files['snap']
        userId = session['user_id']

        filename = secure_filename(file.filename)
        #craet instance
        snap = Snap(request.form['title'], request.form['mini'], filename, userId)
        db.session.add(snap)
        db.session.commit()
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    return redirect(url_for('flow.flows'))

@mod.route('/uploadM', methods=['GET', 'POST'])
def upload2():
    file = request.files['snap']
    userId ="aa"

    filename = secure_filename(file.filename)
    #craet instance
    snap = Snap(request.form['title'], request.form['mini'], filename, userId)
    db.session.add(snap)
    db.session.commit()
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

    a = "b"
    return a

app/users/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, json
from flask_login import (LoginManager, login_required, login_user, 
                         current_user, logout_user, UserMixin)


from app import db
from app.users.models import User

mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('/signUp')
def signUp():
    return render_template('signUp.html')

@mod.route('/register', methods=['POST'])
def register():
    if (User.query.filter_by(userEmail = request.form['email']).first()):
        return 'exist'
    else:
        newUser = User(request.form['email'], request.form['password'])
        db.session.add(newUser)
        db.session.commit()

    return redirect(url_for('index'))

@mod.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(userEmail = email).first()

        if user == None:
            return 'alertNoId'
        if user.userPassword == password:
            session['user_id'] = user.getId()
            return redirect(url_for('flow.flows'))

    return 'alertWrongPassword'

app/templates/flow.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Daily Snap</title>
    <link rel="stylesheet" type="text/css" href="../static/css/flow.css" >
    <link rel="stylesheet" type="text/css" href="../static/css/button.css" >
    <link rel="stylesheet" type="text/css" href="../static/css/snap.css" >
    <link rel="stylesheet" type="text/css" href="../static/css/write.css" >
    <script src="/static/js/snap.js"></script>
    <script src="/static/js/write.js"></script>

</head>
<body>
    <div id = "bg"></div>
    <div id = "write">
        <h1>오늘의 찰칵은 ? </h1>
        <div>
            <form method="post" enctype="multipart/form-data" action="{{url_for('snap.upload')}}" >
                 제목 : <input type="text" name="title" size=40> <br />
                <textarea name="mini" rows="10" cols="50"></textarea><br />
                <input type="file" name="snap">
                <input type="submit" value="done">
            </form>
        </div>
        <button onclick="hideWrite('write', 'bg');">닫기</button>
    </div>
    <div id="top">
        <div id = "moveLeft"><img src="../static/images/moveleft.png"></div>
        <div id = "mid">
            <div id = "topButton">
                <a onclick="showWrite('write', 'bg');" class="hi-icon hi-icon-pencil">write</a>
            </div>
            <div class = "date">
                12월
            </div>

            <div id="flow">
                <ul class="snap moreStyle">
                    {%  for snap in snapList %}
                    <li>
                        <figure>
                            <div><img src="../static/uploads/{{snap.img}}" alt="{{snap.img}}"></div>
                             <figcaption>                        
                                <h3>{{ snap.title }}</h3>
                                <span>{{ snap.mini }}</span>
                                <a href="http://dribbble.com/shots/1116775-Safari">Read More</a>
                             </figcaption>
                        </figure>
                    </li>
                    {% endfor %}
                    <li>
                        <figure>
                            <div><img src="../static/images/5.png" alt="img05"></div>
                             <figcaption>
                                <h3>11/3</h3>
                                <span>밤 막걸리야~~~~~~~밤먹거리는 꿀맛같다. @고속터미널 서래전</span>
                                <a href="http://dribbble.com/shots/1116775-Safari">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
    
                    <li>
                        <figure>
                            <div class="image">
                                <img src ="http://kmomnews.hankyung.com/kmomdata/images/photo/201112/08c1d05365da57e3ff9c93b06ea66b85.jpg">
                            </div>
                            <figcaption>
                                <h3>서태지 콘서트 </h3>
                                <span>서태지 콘서트에 갔다. take one과 함께 대장이 등장할때...눈물이 날 것 같았다.@상암월드컵경기장</span>
                                <a href="http://dribbble.com/shots/1118904-Game-Center">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
                                        <li>
                        <figure>
                            <div><img src="../static/images/5.png" alt="img05"></div>
                             <figcaption>
                                <h3>11/3</h3>
                                <span>밤 막걸리야~~~~~~~밤먹거리는 꿀맛같다. @고속터미널 서래전</span>
                                <a href="http://dribbble.com/shots/1116775-Safari">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
    
                    <li>
                        <figure>
                            <div class="image">
                                <img src ="http://kmomnews.hankyung.com/kmomdata/images/photo/201112/08c1d05365da57e3ff9c93b06ea66b85.jpg">
                            </div>
                            <figcaption>
                                <h3>서태지 콘서트 </h3>
                                <span>서태지 콘서트에 갔다. take one과 함께 대장이 등장할때...눈물이 날 것 같았다.@상암월드컵경기장</span>
                                <a href="http://dribbble.com/shots/1118904-Game-Center">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
                                        <li>
                        <figure>
                            <div><img src="/static/images/5.png" alt="img05"></div>
                             <figcaption>
                                <h3>11/3</h3>
                                <span>밤 막걸리야~~~~~~~밤먹거리는 꿀맛같다. @고속터미널 서래전</span>
                                <a href="http://dribbble.com/shots/1116775-Safari">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
    
                    <li>
                        <figure>
                            <div class="image">
                                <img src ="http://kmomnews.hankyung.com/kmomdata/images/photo/201112/08c1d05365da57e3ff9c93b06ea66b85.jpg">
                            </div>
                            <figcaption>
                                <h3>서태지 콘서트 </h3>
                                <span>서태지 콘서트에 갔다. take one과 함께 대장이 등장할때...눈물이 날 것 같았다.@상암월드컵경기장 </span>
                                <a href="http://dribbble.com/shots/1118904-Game-Center">Read More</a>
                            </figcaption>
                        </figure>
                    </li>
    
                </ul>
            </div>
        </div>
        <div id = "moveRight"><img src="../static/images/moveright.png"></div>
    </div>

    <div id="footer">
        <ul id="introduce">
            <li><a href="#">FINGQOOQ Inc. 2013</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">How it Works</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">help</a></li>
        </ul>
    </div>



</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DailySnap</title>
    <link rel="stylesheet" type="text/css" href="../static/css/home.css" >
    <script src="http://code.jquery.com/jquery-latest.min.js"
        type="text/javascript"></script>
    <script src="../static/js/home.js"></script>
    <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="../static/js/rolling.js"></script>
</head>

<body> 
    <div id = "logo"></div>
    <div id = "slogan">
        <h2>SNAP! Everthing in Your Daily Life!</h2>
    </div>

    
    <section class="sectionBox">
            <div class ="alert">
                <span id = "message"></span>
            </div>
            <div class="insertBox">
                <!--<form method="POST" id="login-form" action="{{url_for('users.login')}}"> -->
                <form id="login-form">
                    <div>
                        <input name="email" placeholder="    E-MAIL"    
                           maxlength="30" type="text" id="id_email">
                        <input type="password" placeholder="    PASSWORD" name="password" id="id_password">
                    </div>
                    <div class="form-actions">
                        <input id="loginButton" type="button" class="login" value="Log In">
                        <br>
                        <div id = "signUp">
                            <span>If you don't have an account, </span>
                            <a href="/users/signUp">Join us!</a>
                        </div>
                        
                    </div>
                </form>
            </div>

    </section>
    <section id="introduce">
        <ul id = "introduceUl">
            <li class="introduceLi"><img src="../static/images/introduce2.png" height="100%" width="100%" /></li>
            <li class="introduceLi"><img src="../static/images/introduce1.png" height="100%" width="100%" /></li>
            <li class="introduceLi"><img src="../static/images/introduce3.jpg" height="100%" width="100%" /></li>
            <li class="introduceLi"><img src="../static/images/introduce4.png" height="100%" width="100%" /></li>
        </ul>
    </section>
    

</body>
</html>

app/templates/signUp.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DailySnap</title>
    <link rel="stylesheet" type="text/css" href="../static/css/signup.css" >
</head>

<body>
<div class="bg"></div>
<div class="box">
    <section class="sectionBox">
        <header>
            <h1 id="logo">DailySnap</h1>
        </header>

        <div class="insertBox">
                <form method="POST" id="login-form" action="{{url_for('users.register')}}">
                Sign Up
                <p><label for="id_email">e-mail : </label> <input name="email" maxlength="30" type="text" id="id_email"></p>
                <p><label for="id_password">password : </label> <input type="password" name="password" id="id_password"></p>

                <p>
                    <input type="submit" class="signUp" value="Sign Up">
                </p>
            </form>

        </div>
    </section>
</div>

</body>
</html>

app/templates/write.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Insert title here</title>
    </head>

    <body>
        <h1>오늘의 찰칵은 ? </h1>
        <div>
            <form method="post" enctype="multipart/form-data" action="{{url_for('snap.upload')}}" >
                 제목 : <input type="text" name="title" size=40> <br />
                <textarea name="mini" rows="10" cols="50">글자를 미리 넣어보자</textarea><br />
                <input type="file" name="snap">
                <input type="submit" value="보내기">
            </form>
        </div>
    </body>
</html>